# Generated by Django 5.0.6 on 2024-07-10 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translate',
            options={'verbose_name': 'Перевод страницы контакты', 'verbose_name_plural': 'Перевод страницы контакты'},
        ),
    ]
