# Generated by Django 5.0.6 on 2024-07-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_translate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='translate',
            name='email_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='translate',
            name='email_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='translate',
            name='hotline_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Горячая линия'),
        ),
        migrations.AddField(
            model_name='translate',
            name='hotline_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Горячая линия'),
        ),
        migrations.AddField(
            model_name='translate',
            name='our_location_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Наша локация'),
        ),
        migrations.AddField(
            model_name='translate',
            name='our_location_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Наша локация'),
        ),
        migrations.AddField(
            model_name='translate',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок банера'),
        ),
        migrations.AddField(
            model_name='translate',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок банера'),
        ),
    ]
