# Generated by Django 5.0.6 on 2024-07-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_chef',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя повара'),
        ),
        migrations.AlterField(
            model_name='popular_category',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Категория блюда'),
        ),
    ]
