# Generated by Django 5.0.6 on 2024-07-16 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_category_special_menu_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='special_menu',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
