# Generated by Django 5.0.6 on 2024-07-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_specialmenu_foods_delete_special_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialmenu_deserts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название десерта')),
                ('image', models.ImageField(upload_to='menu_image_desert/', verbose_name='Изображение десерта')),
                ('makeup1', models.CharField(max_length=55, verbose_name='Состав  1 ')),
                ('makeup2', models.CharField(max_length=55, verbose_name='Состав  2')),
                ('makeup3', models.CharField(max_length=55, verbose_name='Состав  3')),
                ('price', models.IntegerField(verbose_name='Цена ')),
            ],
            options={
                'verbose_name': 'Специальное меню для Б десерта ',
                'verbose_name_plural': 'Специальное меню для Б десерта',
            },
        ),
        migrations.AlterModelOptions(
            name='specialmenu_foods',
            options={'verbose_name': 'Специальное меню для А основного блюда', 'verbose_name_plural': 'Специальное меню для А основных блюд'},
        ),
    ]
