# Generated by Django 5.0.6 on 2024-07-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_specialmenu_deserts_alter_specialmenu_foods_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialmenu_seafood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название  блюда')),
                ('image', models.ImageField(upload_to='menu_image_seafood/', verbose_name='Изображение блюда')),
                ('makeup1', models.CharField(max_length=55, verbose_name='Состав блюда 1 ')),
                ('makeup2', models.CharField(max_length=55, verbose_name='Состав блюда 2')),
                ('makeup3', models.CharField(max_length=55, verbose_name='Состав блюда 3')),
                ('price', models.IntegerField(verbose_name='Цена блюда')),
            ],
            options={
                'verbose_name': 'Специальное меню для В морепродукта ',
                'verbose_name_plural': 'Специальное меню для В морепродуктов',
            },
        ),
    ]
